# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "hashicorp/precise64"

  config.vm.network "private_network", ip: "192.168.50.10", adapter: 2
  config.vm.network "forwarded_port", guest: 5000, host: 5000

  config.vm.provider "virtualbox" do |v|
    v.memory = 512
  end

 config.vm.provision "ansible" do |ansible|
   ansible.playbook = "playbook.yml"
   ansible.extra_vars = { ansible_ssh_user: 'vagrant' }
 end

end
